spring:
  application:
    name: vk-bot-just-ai
  config:
    import: optional:file:.env[.properties]
server:
  port: ${SERVER_PORT}

vk-bot:
  v: ${VK_API_BOT_VERSION}
  secret: ${VK_API_BOT_SECRET}
  accessToken: ${VK_API_BOT_ACCESS_TOKEN}
  confirmation: ${VK_API_BOT_CONFIRMATION}
